# Generated by Django 5.1.2 on 2024-10-27 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentification', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='password',
            field=models.CharField(max_length=25, unique=True),
        ),
    ]
