# Generated by Django 5.1.2 on 2024-10-28 17:03

import django.db.models.deletion
import storage.services
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='File',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to=storage.services.user_directory_path)),
                ('original_title', models.CharField(blank=True, max_length=100)),
                ('comment', models.TextField(blank=True)),
                ('storage_title', models.UUIDField(default=uuid.uuid4)),
                ('size', models.BigIntegerField(blank=True)),
                ('upload_date', models.DateTimeField(auto_now_add=True, null=True)),
                ('last_download', models.DateTimeField(auto_now_add=True, null=True)),
                ('link', models.CharField(blank=True, max_length=254)),
                ('owner', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='files', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
